### ISSUE TITLE
Pergunta, é possível criar um campo GRUPO?

### ISSUE THREAD

**Issue by haarieh** [ResultadosDigitais/rdocs#27]

**Comment by brunogianni** [comment]
@haarieh  tudo bem? campos podem ser criados diretamente no RDStation. Detalhe que nas integrações para mapear a info a este campo, o nome deve ser exatamente o mesmo, ok? Perdão pela demora em retornar btw.

**Comment by haarieh** [comment]
Muito obrigado Bruno pela resposta, tem como selecionar mais de um grupo? 

Att. 

Anderson Silva 

| De: "Bruno Gianni" <notifications@github.com>
| Para: "ResultadosDigitais/rdocs" <rdocs@noreply.github.com>
| Cc: "Haarieh Ltda" <suporte@haarieh.com>
| Enviadas: Terça-feira, 12 de abril de 2016 9:37:43
| Assunto: Re: [ResultadosDigitais/rdocs] Pergunta, é possível criar um campo
| GRUPO? (#27)

| @haarieh tudo bem? campos podem ser criados diretamente no RDStation. Detalhe
| que nas integrações para mapear a info a este campo, o nome deve ser exatamente
| o mesmo, ok? Perdão pela demora em retornar btw.

| —
| You are receiving this because you were mentioned.
| Reply to this email directly or view it on GitHub

**Comment by brunogianni** [comment]
Oi Anderson, pode ser um campo multipla escolha, onde um Lead pode ter mais de uma opção no campo.

**Comment by haarieh** [comment]
Bruno, tem um exemplo fazendo isso pela API? Envio um campo com um array? Ou JSON? 

{ 
GRUPO: [grupo1, grupo2] 
} 

Att. 

Anderson Silva 

| De: "Bruno Gianni" <notifications@github.com>
| Para: "ResultadosDigitais" <rdocs@noreply.github.com>
| Cc: "Haarieh Ltda" <suporte@haarieh.com>
| Enviadas: Quarta-feira, 13 de abril de 2016 16:44:01
| Assunto: Re: [ResultadosDigitais/rdocs] Pergunta, é possível criar um campo
| GRUPO? (#27)

| Oi Anderson, pode ser um campo multipla escolha, onde um Lead pode ter mais de
| uma opção no campo.

| —
| You are receiving this because you were mentioned.
| Reply to this email directly or view it on GitHub

**Comment by brunogianni** [comment]
Apenas para registro Anderson:

"Oi Anderson,

Primeiro deves criar o campo multipla escolha no RD e para enviar a informações o idela é que seja um JSON, onde na info do campo veia um arrayzinho de strings com o mesmo nome das opções cadastradas no RD.

Esse artigo pode ajudar.

Exemplo:
```
 {
    "email":"suporte@resultadosdigitais.com.br",
    "name":"Bruno",
    "identificador":"teste",
    "token_rdstation":"VALORDOTOKEN",
    "GRUPOS":["Grupo X","Grupo Y"]
}
```
Ok?

Um abraço,
Bruno"

**Comment by haarieh** [comment]
Obrigado Bruno!
