### ISSUE TITLE
Undesired POST via RdIntegration

### ISSUE THREAD

**Issue by rinterliche** [ResultadosDigitais/rdocs#28]
The code snipet is automatically interfering in any form POST that has a `input[name="email"]` included. 
In our case we have 2 forms that has the `input[name="email"]` and only one of them have to use the integration.
We need a way to identify the right form to use the RdIntegration.

**Comment by brunogianni** [comment]
@rinterliche thanks for the feedbakc, and indeed, the RdIntegration.integrate binds on all type submit buttons from forms, and if a input[name="email"] it interferes on the flow. the RdIntegration has another method, RdIntegration.post that could be used independently, like [this](https://github.com/ResultadosDigitais/rdocs/blob/master/js_post.md). Does it make sense?

**Comment by rinterliche** [comment]
Yes i think is OK now!
