### ISSUE TITLE
Mensagem depois de form enviado

### ISSUE THREAD

**Issue by claraborges** [ResultadosDigitais/rdocs#31]
Oi, tudo bem?

De acordo com o código disponibilizado, depois que o usuário preenche o formulário, ele é redirecionado para uma página ( <input type="hidden" name="redirect_to" value="http://resultadosdigitais.com.br" />)

Eu queria saber se é possível aparecer uma mensagem de sucesso depois do formulário enviado, sem que o usuário seja redirecionado para uma página de sucesso.

Obrigada,
Clara

**Comment by filipenasc** [comment]
Olá @claraborges, tudo bem?

Em primeiro lugar, nos desculpe na demora pela resposta :confused: 

Utilizando esta biblioteca, só é possível fazer o redirecionamento depois do formulário ser enviado. Até é possível fazer aparecer uma mensagem, mas dependeria de alguém para desenvolver isto e personalizar a nossa biblioteca.

Nos desculpe pelas limitações, vou levar isso como sugestão de melhoria para o nosso time.

Abraço,
Filipe
