### ISSUE TITLE
Campo uuid inexistente

### ISSUE THREAD

**Issue by supwr** [ResultadosDigitais/rdocs#35]
Olá, 

notei que na documentação presente no site o json é um pouco diferente do que existe aqui no GitHub. Na documentação do site existe o campo UUID e aqui não há esse campo. Posso deixar meu sistema preparado para receber UUID ou não? Ficou essa dúvida.

Obrigado!

**Comment by bcgianni** [comment]
Ola @supwr, de fato, acabamos nao atualizando aqui. Obrigado pelo aviso. Podes assumir que o uuid é enviado sim.

**Comment by bcgianni** [comment]
Atualizei o json apresentado aqui na github.
